services:
  portafolio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: cv-djcrespo
    networks:
      - default
    environment:
      - VIRTUAL_HOST=portafolio.djcrespo.dev
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=portafolio.djcrespo.dev
        
    expose:
      - 3000

networks:
  default:
    external:
      name: net-proxy