version: '3.7'
services:
  web:
    image: cv-djcrespo
    restart: unless-stopped
    container_name: cv-render
    networks:
      - default
    environment:
      - VIRTUAL_HOST=devcrespo.tech
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=devcrespo.tech
        
    expose:
      - 3000

networks:
  default:
    external:
      name: net-proxy