version: '3.8'

services:
  portafolio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: cv-djcrespo
    networks:
      - net-proxy
    environment:
      - VIRTUAL_HOST=portafolio.djcrespo.dev
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=portafolio.djcrespo.dev
    expose:
      - 3000

networks:
  net-proxy:
    external: true